### ISSUE TITLE
Cuando se hace quit, quedan subprocesos andando y se imprimen logs

### ISSUE THREAD

**Issue by bliberini** [concurrentes/tp1#16]

**Comment by adrian-mb** [comment]
Lo de los procesos colgados ya **debería** estar resuelto. Lo de los logs, creo que se puede dejar así. Cuando se estén enviando a un log externo no va a pasar nada si no termina instantaneamente al momento de mandar quit; se va a ver "recibido" y "finalizado". Cuando se manda el quit el sistema empieza el proceso de finalización, no necesariamente tiene que bajar instantaneamente; no conozco ningún sistema distribuido que termine de una. Sino se puede hacer más granular y que el chequeo por la señal de finalización se haga más seguido, pero creo que ensuciaría el código.
