### ISSUE TITLE
Contar pasajeros bajados sin ticket y barcos decomisados

### ISSUE THREAD

**Issue by bliberini** [concurrentes/tp1#4]
Según el enunciado, mientras se corre el proceso:

> En todo momento, debe poder consultarse: la cantidad de personas que pagaron multa por viajar
> sin ticket y la cantidad de barcos decomisados.

Habría que agregar como TODO modificar ´Boat::discharge_passengers_without_ticket´ y el método que hagamos para el decomisado para que escriban dos contadores globales cuando se ejecutan.

Mi propuesta es meterlos en una clase singleton aparte, tipo ´RunInfo´, y que ´Engine´ la consulte cuando le envían este comando por consola

**Comment by adrian-mb** [comment]
https://github.com/concurrentes/tp1/commit/a7af31686448128919aa7dbb52adf989e4e5eb2b
